<template>
  <DSList v-if="itemsQuery !== null" :query="itemsQuery">
    <template #anchor="item">
      <router-link :to="[parentPath, item.id, 'details'].join('/')">
        {{ exportDate(item.weekEnding.toDate()) }}
      </router-link>
    </template>
    <template #line1="{ expenses }">
      {{ Object.keys(expenses).length }} expense(s)
    </template>
    <template #actions="item">
      <!-- The attachments.zip file here is generated by the
      updateExpenseTracking() function in the backend. TODO: It may be useful
      to instead have the SQL report generate the file on first run in the
      same method as the Payroll Reports -->
      <a v-if="hasLink(item, 'zip')" download v-bind:href="item['zip']">
        attachments.zip<Icon icon="feather:download" width="24px" />
      </a>
      <action-button
        v-if="canRefresh"
        type="refresh"
        @click="generateAttachmentZip(item, 'weekEnding', true)"
      />
      <a v-if="hasLink(item, 'json')" download v-bind:href="item['json']">
        .json<Icon icon="feather:download" width="24px" />
      </a>
      <action-button
        type="download"
        @click="generatePayablesCSVSQL(item.weekEnding, 'weekly')"
      >
        payablesSQL
      </action-button>
    </template>
  </DSList>
</template>

<script setup lang="ts">
import DSList from "./DSList.vue";
import { ref, computed } from "vue";
import { useRoute } from "vue-router";
import { firebaseApp } from "../firebase";
import { getFirestore, collection, query, orderBy } from "firebase/firestore";
import { useStateStore } from "../stores/state";
import {
  exportDate,
  generatePayablesCSVSQL,
  generateAttachmentZip,
  hasLink,
} from "./helpers";
import ActionButton from "./ActionButton.vue";
import { Icon } from "@iconify/vue";

const store = useStateStore();
const route = useRoute();
const parentPath = ref(route?.matched[route.matched.length - 2]?.path ?? "");
const itemsQuery = ref(
  query(
    collection(getFirestore(firebaseApp), "ExpenseTracking"),
    orderBy("weekEnding", "desc")
  )
);

const canRefresh = computed(() => {
  return (
    Object.prototype.hasOwnProperty.call(store.claims, "admin") &&
    store.claims["admin"] === true
  );
});
</script>
